use super::RunnerCapabilityRequirement::{GitOrShell, InternalPosixScript, OwnerOnly};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, permission_risk, requires_explicit_business_session,
    ToolDefinition, PERMISSION_RISK_WRITE, TOOL_CATEGORY_SESSION, TOOL_CATEGORY_VALIDATION,
};
use crate::metadata::{
    ToolPathHint::None as NoPath, ToolRisk::Read, PROJECT_READ, PROJECT_WRITE, RUNTIME_READ,
    SESSION_COLLABORATE, TOOL_PROVIDER_CONTROL, TOOL_PROVIDER_RUNNER,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    def(
        "start_session",
        super::ToolAuditPolicy::TYPED_CANONICAL,
        ModelHidden,
        TOOL_CATEGORY_SESSION,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::WorkflowManage,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    ),
    adaptive_runtime_direct(
        model_spec(
            def(
                "work_on_project",
                super::ToolAuditPolicy::TYPED_CANONICAL,
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: super::ToolRisk::WorkflowManage,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Support,
                super::ToolActivityInteraction::Meaningful,
            ),
            "Canonical bootstrap for ordinary coding/review. Use project or client_id+path. Omit session_id for a fresh Workflow Session; it does not imply a fresh model context. Exact resume requires an active accessible Session and never guesses prior Session. Defaults return project instructions, workflow guidance, and Skills/Plugin selection metadata. guidance_profile selects direct (default) or code_mode guidance only; it grants no tools, authority, or Session state. Set include_* false only when current model context retains content; otherwise use defaults for a fresh or uncertain model context. Session/window/transport never proves retention; Runtime re-observes instruction files. Skill bodies require skill_read_file; Plugin calls require plugin_tool describe. Checkout does not require Git; mode=worktree uses an exact Git base for an isolated worktree without bypassing Project authority.",
        ).with_gpt_action_description("Start or resume exact project work. Use project or client_id+path; omit session_id for a fresh Workflow Session. Defaults return project/workflow/extension context. worktree mode creates an isolated Runner-managed Git worktree without widening authority."),
        10,
    ),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "finish_coding_task",
                super::ToolAuditPolicy::TYPED_CANONICAL,
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity_kind(super::ToolActivityKind::Review),
            "Return an optional deterministic evidence snapshot for model review, including workspace, validation, jobs, and recorded tool events. The result is advisory: it does not decide task completion, replace direct diff or test review, or generate the user-facing final report.",
        )),
        150,
    ),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "present_work_result",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("project", "/work_result/project"),
                    super::ToolAuditResultField::pointer("session_id", "/work_result/session_id"),
                    super::ToolAuditResultField::pointer("state_version", "/work_result/state_version"),
                    super::ToolAuditResultField::pointer("snapshot_id", "/work_result/final_changes/snapshot_id"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                "workflow",
                Some(InternalPosixScript),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            "Optionally present one exact coding Workflow Session as a persistent read-only Work Result MCP App card when a user-visible work summary is genuinely useful. Requires explicit project + session_id, creates no work, runs no validation/review, changes no Session lifecycle, and grants no authority. The initial Work Result includes eligible frozen final changes for lazy in-card diff reads; do not call merely to acknowledge a clean worktree and do not call repeatedly to refresh. User-driven app-only refresh updates live workspace, validation, and review without replacing the card's frozen snapshot. Presentation is UX only, never a correctness requirement; repeated explicit presentation may create another Host card.",
        ))
        .with_gpt_action_unsupported(),
        155,
    ),
    def(
        "work_result_state",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::pointer("project", "/work_result/project"),
            super::ToolAuditResultField::pointer("session_id", "/work_result/session_id"),
            super::ToolAuditResultField::pointer("state_version", "/work_result/state_version"),
            super::ToolAuditResultField::value("error_kind"),
        ]),
        ModelHidden,
        "workflow",
        Some(GitOrShell),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_activity(
        super::ToolActivityPresentation::Transport,
        super::ToolActivityInteraction::NonMeaningful,
    ),
    def(
        "changes_file_diff",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::pointer("project", "/changes_file_diff/project"),
            super::ToolAuditResultField::pointer("session_id", "/changes_file_diff/session_id"),
            super::ToolAuditResultField::pointer("snapshot_id", "/changes_file_diff/snapshot_id"),
            super::ToolAuditResultField::pointer("path", "/changes_file_diff/path"),
            super::ToolAuditResultField::value("error_kind"),
        ]),
        ModelHidden,
        "workflow",
        Some(InternalPosixScript),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_activity(
        super::ToolActivityPresentation::Transport,
        super::ToolActivityInteraction::NonMeaningful,
    ),
    requires_explicit_business_session(model_spec(
        def(
            "session_summary",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Return a bounded structured summary from the session ledger for an explicit session_id: recorded events, message-board summary, task mode, guards, and lifecycle. Uses durable ledger data where session persistence is configured.",
    )),
    adaptive_runtime_direct(
        model_spec(
            def(
                "native_thread_read",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("resolved"),
                    super::ToolAuditResultField::value("next_cursor"),
                    super::ToolAuditResultField::value("quota_mode"),
                    super::ToolAuditResultField::value("model_turn_started"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&[
                    "session",
                    "cursor",
                ])),
                ModelVisible,
                TOOL_CATEGORY_SESSION,
                Some(OwnerOnly),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Read canonical native Codex thread metadata plus one recent item page through app-server thread/read and thread/items/list. The Bridge strips native filesystem paths, MCP arguments/results, and other raw payloads; starts no Codex model turn.",
        ),
        34,
    ),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "update_session_context",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Update Session defaults. Binding execution_context.resource selects an already active Runner-local named SSH resource; for a new explicit target use ssh_resource list/register and restart the Runner first, then list and bind the active name. open_session_shell uses that Session binding. Requires an authorized project matching the exact Session project; cross-project escape is not supported. Context and event commit under the store lock; the background writer persists, so success does not mean disk flush. Never falls back and never creates unknown Sessions.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "close_session",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.persistent_shell(super::PersistentShellEvidenceAction::Close).lifecycle(super::ToolSessionLifecycleEffect::IdempotentClose),
            ),
            "Explicitly close a workflow session (Active to Closed) for a required session_id. Query remains available; write/shell/mutation tools are denied. Idempotent when already closed; unknown ids fail without create. finish_coding_task does not close.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "validation_summary",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_VALIDATION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::Meaningful,
        ),
        "Read bounded structured validation evidence already recorded in an explicit project-scoped session ledger. Does not run Cargo or shell commands, enqueue a Runner request, read project files, mutate the workspace, or replace finish_coding_task.",
    )),
    requires_explicit_business_session(model_spec(
        def(
            "post_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::pointer("kind", "/message/kind"),
                super::ToolAuditResultField::pointer("status", "/message/status"),
                super::ToolAuditResultField::pointer("requires_ack", "/message/requires_ack"),
                super::ToolAuditResultField::pointer("author_session_id", "/message/author_session_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
        ),
        "Post a bounded collaboration message (todo, question, progress, guidance, risk, or decision). Any message may request request-scoped ACK; ACK proves only current model-context retention and neither resolves nor gates work. Use complete_session_message to atomically answer and resolve a finished todo.",
    )),
    model_spec(
        def(
            "post_peer_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::value("sender_peer_id"),
                super::ToolAuditResultField::value("recipient_peer_id"),
                super::ToolAuditResultField::value("requires_ack"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Send a bounded message to a principal-scoped peer window discovered through peer_awareness. Routing does not require Project equality, so a Project/worktree change alone does not invalidate the retained route; it grants no access to the recipient's Project, Workflow Session, files, or assignment authority. Ordinary messages are projected once; requires_ack messages repeat while retained whenever the recipient omits the request-scoped ACK.",
    ),
    requires_explicit_business_session(model_spec(
        def(
            "list_session_messages",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::array_len("message_count", "messages"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Read bounded session-local messages with exact filters. For an executable todo, prefer get_session_assignment so the todo, all retained direct replies, and its completion fence come from one store snapshot.",
    )),
    requires_explicit_business_session(model_spec(
        def(
            "get_session_assignment",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::array_len("direct_reply_count", "direct_replies"),
                super::ToolAuditResultField::string_present("assignment_fence_present", "assignment_fence"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Atomically read one exact open todo plus all retained direct replies and return the opaque assignment_fence required by complete_session_message. Unrelated Session traffic and ACK bookkeeping do not stale it; incomplete retained assignment history fails closed.",
    )),
    requires_explicit_business_session(model_spec(
        def(
            "observe_session_messages",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::array_len("message_count", "messages"),
                super::ToolAuditResultField::value("changed"),
                super::ToolAuditResultField::value("history_lost"),
                super::ToolAuditResultField::value("has_more"),
                super::ToolAuditResultField::value("wait_outcome"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Observe Session message-state delta after an opaque durable cursor. No token establishes the current baseline and returns no history; token calls may wait once for change. Reports retention loss; never a subscription, delivery receipt, or model-context proof.",
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "resolve_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::pointer("status", "/message/status"),
                super::ToolAuditResultField::pointer("resolved_by_message_id", "/message/resolved_by_message_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Mark a session-local ledger message resolved. Idempotent when the message is already resolved; metadata-only and never modifies project files.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "complete_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::value("answer_message_id"),
                super::ToolAuditResultField::value("completion_id"),
                super::ToolAuditResultField::value("replayed"),
                super::ToolAuditResultField::pointer("author_session_id", "/answer/author_session_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::FencedReplay,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Atomically answer and resolve one exact open todo. expected_assignment_fence is required and must be the exact opaque fence from get_session_assignment; completion_key separately keeps uncertain-result retries idempotent.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "session_discussion_summary",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("success"),
                    super::ToolAuditResultField::value("session_id"),
                    super::ToolAuditResultField::value("counts"),
                    super::ToolAuditResultField::array_len("open_todo_count", "open_todos"),
                    super::ToolAuditResultField::array_len("recent_answer_count", "recent_answers"),
                    super::ToolAuditResultField::array_len("recent_completion_count", "recent_completions"),
                ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Return a bounded structured aggregate of session-local discussion from the recorded session ledger. Does not call an LLM or generate natural-language summaries.",
        )),
        15,
    ),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "session_handoff_summary",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("project"),
                super::ToolAuditResultField::value("lifecycle"),
                super::ToolAuditResultField::value("counts"),
                super::ToolAuditResultField::array_len("open_todo_count", "open_todos"),
                super::ToolAuditResultField::array_len("recent_answer_count", "recent_answers"),
                super::ToolAuditResultField::array_len("recent_completion_count", "recent_completions"),
                super::ToolAuditResultField::value("diagnostic"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::Meaningful,
        ),
            "Explicit read-only recovery for genuinely missing task context or an explicit handoff; requires the exact session_id. Do not use as routine progress/status polling or to establish a Session baseline when current context is coherent. Defaults to identity plus deterministic handoff_brief, hard-bounded at 8 KiB: task instructions, workspace, progress, validation, jobs, collaboration attention, next actions and basis completeness. Omitted project uses the authorized Session Project. diagnostic=true adds detailed ledger and closeout evidence. A concurrent Session change marks the basis incomplete; re-observe before dependent work. No checkpoint allocation, ACK token, or authority grant.",
        ).with_gpt_action_description("Recover missing task context or perform an explicit handoff for an exact session_id. Do not use for routine progress/status polling or to establish a baseline. Returns a bounded handoff_brief; diagnostic=true adds detailed evidence. Check basis completeness before dependent work. Read-only.")),
        16,
    ),
];
