use super::RunnerCapabilityRequirement::{FileRead, OwnerOnly, SkillManagement};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, require_all_scopes, ToolDefinition,
    ToolOperatorExtensionFamily, TOOL_CATEGORY_RUNTIME,
};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{JobRun, Read, SkillManage},
    ADMIN, JOB_RUN, PROJECT_READ, TOOL_PROVIDER_RUNNER,
};

/// Project Skill runtime tools. `skill_load` is the narrow direct model path;
/// the broader discovery/read compatibility tools remain hidden operator
/// extensions. Kernel capability and authority gates remain authoritative.
pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    adaptive_runtime_direct(
        model_spec(
            def(
                "skill_load",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("catalog_revision"),
                    super::ToolAuditResultField::value("skill_id"),
                    super::ToolAuditResultField::value("source_scope"),
                    super::ToolAuditResultField::value("trust"),
                    super::ToolAuditResultField::value("package_revision"),
                    super::ToolAuditResultField::value("definition_revision"),
                    super::ToolAuditResultField::value("path"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&["name"]))
                .context(super::ToolAuditContextPolicy::Fields(&[
                    super::ToolAuditResultField::value("catalog_revision"),
                    super::ToolAuditResultField::value("skill_id"),
                    super::ToolAuditResultField::value("source_scope"),
                    super::ToolAuditResultField::value("trust"),
                    super::ToolAuditResultField::value("package_revision"),
                    super::ToolAuditResultField::value("definition_revision"),
                    super::ToolAuditResultField::value("path"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])),
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                Some(FileRead),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Load one uniquely named Skill by exact Unicode case folding. Returns its descriptor, bounded SKILL.md, and revisions in one read-only Project call. Missing, ambiguous, or truncated discovery fails closed; scripts and other Skill resources are never executed.",
        ),
        27,
    ),
    adaptive_runtime_direct(
        model_spec(
            def(
                "native_skill_list",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("total_count"),
                    super::ToolAuditResultField::value("returned_count"),
                    super::ToolAuditResultField::value("next_offset"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&["query"])),
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                Some(OwnerOnly),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Search the complete native Codex Skill catalog on the same Runner with bounded pagination. Returns pathless names, descriptions, scope/plugin metadata, and opaque native_skill_id values; starts no Codex model turn.",
        ),
        28,
    ),
    adaptive_runtime_direct(
        model_spec(
            def(
                "native_skill_load",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("native_skill_id"),
                    super::ToolAuditResultField::value("scope"),
                    super::ToolAuditResultField::value("plugin_id"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("bytes"),
                    super::ToolAuditResultField::value("start_line"),
                    super::ToolAuditResultField::value("end_line"),
                    super::ToolAuditResultField::value("total_lines"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("candidates_truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&[
                    "name",
                    "native_skill_id",
                ])),
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                Some(OwnerOnly),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Load one native Codex Skill through the same Runner's Context Bridge by exact name, optionally using an opaque native_skill_id when duplicate names are reported. Supports pathless start_line/limit continuation and starts no Codex model turn.",
        ),
        29,
    ),
    adaptive_runtime_direct(
        model_spec(
            def(
                "native_knowledge_load",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("manifest_sha256"),
                    super::ToolAuditResultField::value("entry_sha256"),
                    super::ToolAuditResultField::value("start_line"),
                    super::ToolAuditResultField::value("end_line"),
                    super::ToolAuditResultField::value("total_lines"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&["key"])),
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                Some(OwnerOnly),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Load one project knowledge entry using only its reuse-manifest semantic key. WebCodex resolves the entry on the same Runner, requires it to remain inside the Project, checks the manifest entry hash when present, and supports line continuation by key without exposing the manifest or entry path.",
        ),
        35,
    ),
    adaptive_runtime_direct(
        require_all_scopes(
            model_spec(
                def(
                    "run_skill_resource",
                    super::ToolAuditPolicy::typed_fields(&[
                        super::ToolAuditResultField::value("skill_id"),
                        super::ToolAuditResultField::value("skill_path"),
                        super::ToolAuditResultField::value("skill_sha256"),
                        super::ToolAuditResultField::value("skill_trust"),
                        super::ToolAuditResultField::value("skill_definition_revision"),
                        super::ToolAuditResultField::value("skill_package_revision"),
                        super::ToolAuditResultField::value("execution_state"),
                        super::ToolAuditResultField::value("exit_code"),
                        super::ToolAuditResultField::value("failure_kind"),
                        super::ToolAuditResultField::value("tool_failure"),
                    ])
                    .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&[
                        "args",
                        "process_summary",
                    ])),
                    ModelVisible,
                    TOOL_CATEGORY_RUNTIME,
                    Some(super::RunnerCapabilityRequirement::SkillResourceExecution),
                    TOOL_PROVIDER_RUNNER,
                    super::ToolSemanticContract {
                        effect: super::ToolEffect::Execute,
                        risk: JobRun,
                        approval: super::ToolApprovalPolicy::Standard,
                        idempotency: super::ToolIdempotency::NonIdempotent,
                    },
                    Some(JOB_RUN),
                    true,
                    NoPath,
                    true,
                    true,
                    super::ToolSessionEvidencePolicy::NONE,
                ),
                "Execute one supported scripts/*.py or scripts/*.sh resource from a trusted Runner-configured live Skill or Runner-installed managed Skill without exposing or retransmitting its source through model context. Configured Skills are live resources: expected_definition_revision fences the selected SKILL.md definition, while resource bytes are read at execution and package-relative helpers remain live; skill_sha256 reports the exact main-script bytes executed. Managed installed Skills additionally require expected_package_revision and execute against a Runner-owned immutable package snapshot. The Runner preserves the selected Skill script/package identity for __file__, Python sibling imports, and shell $0-relative helpers while keeping the requested Project cwd; project-content Skills are rejected.",
            )
            .with_gpt_action_description("Execute a trusted Runner Skill script. Configured Skills are live and definition-fenced by expected_definition_revision; managed Skills additionally require expected_package_revision. WebCodex selects the .py/.sh interpreter; project-content Skills are rejected.")
            .with_execution(super::ToolExecutionContract::new(
                super::ToolExecutionForm::NativeArgv,
                super::ToolExecutionLifetime::Runner,
                super::ToolExecutionStart::SyncFirst,
                super::ToolExecutionContinuation::ObserveJobs,
            )),
            &[PROJECT_READ, JOB_RUN],
        ),
        71,
    ),
    def(
        "skill_list",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])
        .context(super::ToolAuditContextPolicy::Fields(&[
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillRuntime),
    def(
        "skill_read_file",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("source_scope"),
            super::ToolAuditResultField::value("trust"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])
        .context(super::ToolAuditContextPolicy::Fields(&[
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillRuntime),
    def(
        "skill_versions",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_install",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("artifact_sha256"),
            super::ToolAuditResultField::value("file_count"),
            super::ToolAuditResultField::value("total_bytes"),
            super::ToolAuditResultField::value("installed"),
            super::ToolAuditResultField::value("activated"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_activate",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("previous_active_package_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("changed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_remove_revision",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("removed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        true,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
];
